[project]
name = "admin_helper_cli"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Julius Koenig", email = "info@bastelquartier.de" },
]
dependencies = [
    "fastapi>=0.135.2",
    "jinja2>=3.1.6",
    "nicegui>=3.12.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "rich>=14.3.3",
    "typer>=0.24.1",
    "uvicorn>=0.42.0",
]
requires-python = ">=3.12"

[build-system]
requires = ["uv_build>=0.10.9,<0.12.0"]
build-backend = "uv_build"

[project.scripts]
admin-helper-cli = "admin_helper_cli.__main__:cli_app"
